# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master, development]
  pull_request:
    branches: [ master, development]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]
      
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 13    
      
    - name: Install dependencies
      run: yarn
      
    - name: Check tests
      run: yarn test
  
    - name: Check linting
      run: yarn lint
      
    - name: Check commit message
      uses: wagoid/commitlint-github-action@v2